//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomRec.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandomRec.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse....
        /// </summary>
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select folder for recordings.
        /// </summary>
        public static string BrowseDialogTitle {
            get {
                return ResourceManager.GetString("BrowseDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Camera:.
        /// </summary>
        public static string CameraLabel {
            get {
                return ResourceManager.GetString("CameraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duration (sec):.
        /// </summary>
        public static string DurationLabel {
            get {
                return ResourceManager.GetString("DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на camera not selected.
        /// </summary>
        public static string ErrCameraNotSelected {
            get {
                return ResourceManager.GetString("ErrCameraNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на folder not set.
        /// </summary>
        public static string ErrFolderNotSet {
            get {
                return ResourceManager.GetString("ErrFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на invalid duration.
        /// </summary>
        public static string ErrInvalidDuration {
            get {
                return ResourceManager.GetString("ErrInvalidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на invalid interval.
        /// </summary>
        public static string ErrInvalidInterval {
            get {
                return ResourceManager.GetString("ErrInvalidInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на microphone not selected.
        /// </summary>
        public static string ErrMicNotSelected {
            get {
                return ResourceManager.GetString("ErrMicNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder:.
        /// </summary>
        public static string FolderLabel {
            get {
                return ResourceManager.GetString("FolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interval (min):.
        /// </summary>
        public static string IntervalLabel {
            get {
                return ResourceManager.GetString("IntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language:.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cameras found: {0}.
        /// </summary>
        public static string LogCamerasFound {
            get {
                return ResourceManager.GetString("LogCamerasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First recording — starting now.
        /// </summary>
        public static string LogFirstNow {
            get {
                return ResourceManager.GetString("LogFirstNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid settings: {0}.
        /// </summary>
        public static string LogInvalidSettings {
            get {
                return ResourceManager.GetString("LogInvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loop error: {0}.
        /// </summary>
        public static string LogLoopError {
            get {
                return ResourceManager.GetString("LogLoopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microphones found: {0}.
        /// </summary>
        public static string LogMicrophonesFound {
            get {
                return ResourceManager.GetString("LogMicrophonesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Muxing failed: {0}.
        /// </summary>
        public static string LogMuxingFailed {
            get {
                return ResourceManager.GetString("LogMuxingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next recording in {0} min.
        /// </summary>
        public static string LogNextIn {
            get {
                return ResourceManager.GetString("LogNextIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preview start error: {0}.
        /// </summary>
        public static string LogPreviewError {
            get {
                return ResourceManager.GetString("LogPreviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✓ Saved: {0}.
        /// </summary>
        public static string LogRecordingSaved {
            get {
                return ResourceManager.GetString("LogRecordingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ▶ Recording started ({0}s).
        /// </summary>
        public static string LogRecordingStarted {
            get {
                return ResourceManager.GetString("LogRecordingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Screenshot failed: {0}.
        /// </summary>
        public static string LogScreenshotFailed {
            get {
                return ResourceManager.GetString("LogScreenshotFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recording service started.
        /// </summary>
        public static string LogServiceStarted {
            get {
                return ResourceManager.GetString("LogServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recording service stopped.
        /// </summary>
        public static string LogServiceStopped {
            get {
                return ResourceManager.GetString("LogServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microphone:.
        /// </summary>
        public static string MicrophoneLabel {
            get {
                return ResourceManager.GetString("MicrophoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preview.
        /// </summary>
        public static string PreviewPlaceholder {
            get {
                return ResourceManager.GetString("PreviewPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на REC.
        /// </summary>
        public static string RecLabel {
            get {
                return ResourceManager.GetString("RecLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save screenshots from camera.
        /// </summary>
        public static string ScreenshotsCheckbox {
            get {
                return ResourceManager.GetString("ScreenshotsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Silent mode (no notifications).
        /// </summary>
        public static string SilentModeCheckbox {
            get {
                return ResourceManager.GetString("SilentModeCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string StopButton {
            get {
                return ResourceManager.GetString("StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на random recorder.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
